# Generated by Django 6.0.6 on 2026-07-03 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetterAuthUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(db_column='emailVerified', default=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='BetterAuthVerification',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('identifier', models.TextField()),
                ('value', models.TextField()),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
                ('created_at', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'verification',
            },
        ),
        migrations.CreateModel(
            name='BetterAuthAccount',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_id', models.CharField(db_column='accountId', max_length=255)),
                ('provider_id', models.CharField(db_column='providerId', max_length=255)),
                ('access_token', models.TextField(blank=True, db_column='accessToken', null=True)),
                ('refresh_token', models.TextField(blank=True, db_column='refreshToken', null=True)),
                ('id_token', models.TextField(blank=True, db_column='idToken', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_column='expiresAt', null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='BetterAuthSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
                ('ip_address', models.CharField(blank=True, db_column='ipAddress', max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='userAgent', null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
